### ISSUE TITLE
Cannot Run it locally on Windows - make × ERR  not found: make-$(SRC_DIR)/node_modules

### ISSUE THREAD

**Issue by imanradu** [benc-uk/postman-prometheus#8]
I'm trying to run the application locally on Windows but it returns this error:

`make run
make i info Invoking run target
(node:13324) UnhandledPromiseRejectionWarning: undefined
(Use `node --trace-warnings ...` to show where the warning was created)
(node:13324) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13324) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
make × ERR  not found: make-$(SRC_DIR)/node_modules`

## Expected Behavior
I do not understand from the current README file what additional configurations need to be done before and how can it be run locally.

I would like to run the application locally for a postman collection and provide the metrics to Prometheus using this service. If possible I request a  README update with more specific steps for this case.

## Actual Behavior

SRC_DIR is not recognized for > make run

`run: $(SRC_DIR)/node_modules .EXPORT_ALL_VARIABLES ## 🥈 Run locally using Node.js
	cd $(SRC_DIR); npm start`

## Steps to Reproduce the Problem

> clone {LINK}
> cd {repoPath}
// hardcoded values of collectionFile and envFile in server.js 
> make run

## Environment Details

- Version: 1.2.1
- Operating System: Windows
- Platform: locally
- Other Components:   npm: '6.14.12', make --version 0.8.1, newman --version 5.3.2

**Comment by benc-uk** [comment]
I assume you're using PowerShell or even the legacy cmd prompt, the makefile will not work here.
Use WSL if you are on Windows
